#!/bin/sh
set -e
if [ "$1" = "purge" ] ; then
        update-rc.d pifand remove >/dev/null
fi
if [ -d /run/systemd/system ] && [ "$1" = remove ]; then
        systemctl --system daemon-reload >/dev/null || true
fi
if [ "$1" = "remove" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper mask 'pifand.service' >/dev/null || true
        fi
fi

if [ "$1" = "purge" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper purge 'pifand.service' >/dev/null || true
                deb-systemd-helper unmask 'pifand.service' >/dev/null || true
        fi
fi
